import type { BlogPost } from './types'

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'international-schools-bangkok-guide',
    title: 'International Schools in Bangkok: The Complete Expat Guide 2026',
    excerpt: 'Harrow, Shrewsbury, NIST, Bangkok Patana — Bangkok has over 80 international schools with fees from USD 7,000 to USD 39,000. Here is how to choose the right one for your family.',
    category: 'guide',
    readTime: 10,
    author: 'Nana',
    publishedAt: '2026-03-28',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'singapore-international-school-guide-2025',
    title: 'Singapore International Schools: The 2026 Parent Guide',
    excerpt: 'SAS, UWCSEA, Tanglin — ranked by curriculum, fees, and waiting list reality. Fees run SGD 20,000–52,000 per year. Here is how to get a place.',
    category: 'guide',
    readTime: 11,
    author: 'Nana',
    publishedAt: '2026-03-20',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'ib-vs-igcse-parents-guide',
    title: 'IB vs IGCSE: Which Is Right for Your Child?',
    excerpt: 'Parents ask this every week. Here is the honest breakdown — university acceptance, workload, and what admissions officers actually say.',
    category: 'guide',
    readTime: 9,
    author: 'Nana',
    publishedAt: '2026-03-15',
    image: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'international-school-fees-asia',
    title: 'International School Fees in Asia: What You Will Actually Pay in 2026',
    excerpt: 'Singapore to Jakarta, Bangkok to KL — a complete fee comparison across Asia\'s major expat cities. Includes hidden costs, debentures, and what each price point actually gets you.',
    category: 'guide',
    readTime: 8,
    author: 'Nana',
    publishedAt: '2026-03-10',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'moving-bangkok-kids-schools',
    title: 'Moving to Bangkok With Kids: Schools, Neighbourhoods, and What to Do First',
    excerpt: 'The school decision determines where you live in Bangkok — not the other way around. Here is exactly how to approach the move, from application timeline to EAL support.',
    category: 'guide',
    readTime: 8,
    author: 'Nana',
    publishedAt: '2026-03-05',
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'ib-schools-thailand',
    title: 'IB Schools in Thailand: Every Authorised School, Ranked Honestly',
    excerpt: 'Thailand has 60+ IB-authorised schools with fees from THB 250,000 to THB 880,000 per year. Here are the ones with genuine IB programmes — and the questions to ask to tell the difference.',
    category: 'picks',
    readTime: 9,
    author: 'Nana',
    publishedAt: '2026-02-28',
    image: 'https://images.unsplash.com/photo-1543877087-ebf71fde2be1?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'international-schools-kuala-lumpur',
    title: 'International Schools in Kuala Lumpur: The Expat Family Guide',
    excerpt: 'KL has the best value international schools in Southeast Asia — fees USD 10,000–21,000 at schools like Garden International and Alice Smith. Here is everything you need to know.',
    category: 'guide',
    readTime: 9,
    author: 'Nana',
    publishedAt: '2026-02-20',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'british-vs-american-curriculum',
    title: 'British vs American Curriculum International School: How to Choose',
    excerpt: 'A-levels, IGCSEs, AP courses — the curriculum you choose affects where your child can apply to university. Here is the honest comparison, with schools that offer both.',
    category: 'guide',
    readTime: 7,
    author: 'Nana',
    publishedAt: '2026-02-12',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'international-schools-jakarta',
    title: 'International Schools in Jakarta: What Expat Families Need to Know',
    excerpt: 'Jakarta\'s traffic makes school location critical. Fees run USD 8,000–26,000. Here are the schools that expat families actually recommend — and the ones to avoid.',
    category: 'guide',
    readTime: 8,
    author: 'Nana',
    publishedAt: '2026-02-05',
    image: 'https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'boarding-schools-asia',
    title: 'Boarding Schools in Asia: The Complete Guide for Expat Families',
    excerpt: 'Marlborough Malaysia, Shrewsbury Bangkok — boarding in Asia costs USD 27,000–41,000 per year, 40% less than UK equivalents. Here is what the options are and how they compare.',
    category: 'picks',
    readTime: 8,
    author: 'Nana',
    publishedAt: '2026-01-28',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'affordable-international-schools-bangkok',
    title: 'Affordable International Schools in Bangkok Under USD 14,000',
    excerpt: 'You do not need to pay USD 35,000 per year for a good international education in Bangkok. Here are the schools with genuine quality at THB 250,000–500,000 per year.',
    category: 'guide',
    readTime: 7,
    author: 'Nana',
    publishedAt: '2026-01-20',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'international-schools-ho-chi-minh',
    title: 'International Schools in Ho Chi Minh City: The 2026 Parent Guide',
    excerpt: 'HCMC\'s international school market has improved dramatically. Fees USD 7,000–22,000. Here are the schools worth considering and what to know before you move.',
    category: 'guide',
    readTime: 7,
    author: 'Nana',
    publishedAt: '2026-01-12',
    image: 'https://images.unsplash.com/photo-1583417267826-aebc4d1542e1?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'how-to-choose-international-school',
    title: 'How to Choose an International School Abroad: A Practical Framework',
    excerpt: 'Four questions that cut through the noise: curriculum, quality, culture, and getting a place. Here is how to assess any international school honestly before you commit.',
    category: 'guide',
    readTime: 8,
    author: 'Nana',
    publishedAt: '2026-01-05',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80&auto=format&fit=crop',
  },
  {
    slug: 'best-boarding-schools-uk-international-families',
    title: 'The Best UK Boarding Schools for International Families in 2026',
    excerpt: 'From Harrow to Millfield — Nana ranks the schools with the strongest international communities, EAL support, and visa track records. Fees £22,000–£52,000.',
    category: 'picks',
    readTime: 7,
    author: 'Nana',
    publishedAt: '2025-12-10',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80&auto=format&fit=crop',
  },
]

export const CATEGORY_LABELS: Record<BlogPost['category'], string> = {
  thai: 'Spotlight',
  guide: 'Parent Guide',
  picks: "Nana's Picks",
  visa: 'Visa & Entry',
  scholar: 'Scholarships',
}
