export interface RegionCountry {
  name: string
  slug: string
  flagCode: string
  schoolCount: number
  cities: string
  nanaNote: string
  imageUrl: string
  isFeatured?: boolean
  hasVisitedRibbon?: boolean
}

export interface RegionData {
  id: string
  slug: string
  name: string
  nameItalicPart: string
  heroImage: string
  description: string
  nanaQuoteLabel: string
  nanaQuote: string
  nanaQuoteStrong: string
  stats: {
    countries: number
    schools: number
  }
  countries: RegionCountry[]
}

export const ALL_REGION_STUBS = [
  { slug: 'southeast-asia', name: 'South East Asia', sub: '9 countries', count: 676 },
  { slug: 'europe', name: 'Europe', sub: 'incl. UK, Spain, Switzerland', count: 1264 },
  { slug: 'middle-east', name: 'Middle East', sub: 'UAE, Qatar, KSA', count: 448 },
  { slug: 'east-asia', name: 'East Asia', sub: 'China, Japan, HK, Korea', count: 955 },
  { slug: 'oceania', name: 'Oceania', sub: 'Australia, New Zealand', count: 224 },
  { slug: 'americas', name: 'Americas', sub: 'USA, Canada + more', count: 192 },
  { slug: 'south-asia', name: 'South Asia', sub: 'India, Pakistan + more', count: 446 },
  { slug: 'africa', name: 'Africa', sub: 'Kenya, Egypt, Nigeria', count: 144 },
  { slug: 'central-asia', name: 'Central Asia', sub: 'Kazakhstan, Uzbekistan + more', count: 130 },
]

export const REGIONS_DATA: RegionData[] = [
  {
    id: 'southeast-asia',
    slug: 'southeast-asia',
    name: 'South East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1400&q=85&auto=format&fit=crop',
    description: '10 countries across the region — from Singapore\'s world-class international campuses to Thailand\'s fast-growing local schools.',
    nanaQuoteLabel: 'Nana\'s take on South East Asia',
    nanaQuote: '"For families considering staying in Asia, Singapore is my first recommendation for a truly world-class English-medium education. Malaysia is excellent value. Thailand has strong schools in Bangkok, Chiang Mai and Phuket."',
    nanaQuoteStrong: 'Singapore is my first recommendation',
    stats: { countries: 10, schools: 750 },
    countries: [
      {
        name: 'Thailand',
        slug: 'thailand',
        flagCode: 'th',
        schoolCount: 330,
        cities: 'Bangkok, Chiang Mai, Phuket',
        nanaNote: '"Excellent value international community. Bangkok, Chiang Mai and Phuket all have strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Singapore',
        slug: 'singapore',
        flagCode: 'sg',
        schoolCount: 206,
        cities: 'City-state',
        nanaNote: '"World-class options. Strong British curriculum — best outside the UK."',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Indonesia',
        slug: 'indonesia',
        flagCode: 'id',
        schoolCount: 143,
        cities: 'Jakarta, Bali',
        nanaNote: '"Strong choices in Jakarta. BIS and SIS are both solid."',
        imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Malaysia',
        slug: 'malaysia',
        flagCode: 'my',
        schoolCount: 160,
        cities: 'Kuala Lumpur, Penang',
        nanaNote: '"Marlborough Malaysia is excellent value — a fraction of UK fees."',
        imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Philippines',
        slug: 'philippines',
        flagCode: 'ph',
        schoolCount: 37,
        cities: 'Manila, Cebu',
        nanaNote: '"English-medium and affordable. Manila has a growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Vietnam',
        slug: 'vietnam',
        flagCode: 'vn',
        schoolCount: 80,
        cities: 'Ho Chi Minh City, Hanoi',
        nanaNote: '"Fast-growing expat scene. Good IB options in Ho Chi Minh City."',
        imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Myanmar',
        slug: 'myanmar',
        flagCode: 'mm',
        schoolCount: 16,
        cities: 'Yangon',
        nanaNote: '"A handful of solid international schools in Yangon for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cambodia',
        slug: 'cambodia',
        flagCode: 'kh',
        schoolCount: 18,
        cities: 'Phnom Penh',
        nanaNote: '"Phnom Penh has a growing international school scene for NGO and expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1538193268820-b27e6a71a4ff?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brunei',
        slug: 'brunei',
        flagCode: 'bn',
        schoolCount: 9,
        cities: 'Bandar Seri Begawan',
        nanaNote: '"Small but well-resourced market. Excellent for families in the energy sector."',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Laos',
        slug: 'laos',
        flagCode: 'la',
        schoolCount: 4,
        cities: 'Vientiane',
        nanaNote: '"Small international community in Vientiane. Good options for NGO and expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Timor-Leste',
        slug: 'timor-leste',
        flagCode: 'tl',
        schoolCount: 1,
        cities: 'Dili',
        nanaNote: '"Dili has a small international school for the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brunei Darussalam',
        slug: 'brunei-darussalam',
        flagCode: 'bn',
        schoolCount: 3,
        cities: 'Bandar Seri Begawan',
        nanaNote: '"Brunei has international schools with a strong British curriculum tradition."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'europe',
    slug: 'europe',
    name: 'Europe',
    nameItalicPart: 'Europe',
    heroImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1400&q=85&auto=format&fit=crop',
    description: '35+ countries with over 1,300 international schools — from Britain\'s centuries-old boarding tradition to Switzerland\'s elite alpine campuses.',
    nanaQuoteLabel: 'Nana\'s take on Europe',
    nanaQuote: '"For families who want the very best boarding education, Europe is unbeatable. The UK has boarding schools for every personality. Switzerland offers a unique multilingual environment with stunning campuses."',
    nanaQuoteStrong: 'Europe is unbeatable',
    stats: { countries: 35, schools: 2500 },
    countries: [
      {
        name: 'United Kingdom',
        slug: 'united-kingdom',
        flagCode: 'gb',
        schoolCount: 2077,
        cities: 'London, Surrey, Berkshire',
        nanaNote: '"Top boarding tradition. Strong IB and A-Levels. I have visited every school personally."',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
        hasVisitedRibbon: true,
      },
      {
        name: 'Spain',
        slug: 'spain',
        flagCode: 'es',
        schoolCount: 424,
        cities: 'Barcelona, Madrid, Málaga',
        nanaNote: '"Spain has a large, well-established international school market. Barcelona and Madrid are top destinations for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Switzerland',
        slug: 'switzerland',
        flagCode: 'ch',
        schoolCount: 202,
        cities: 'Lausanne, Montreux, Leysin',
        nanaNote: '"Premium boarding, multilingual, stunning alpine campuses. Worth every franc."',
        imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Poland',
        slug: 'poland',
        flagCode: 'pl',
        schoolCount: 114,
        cities: 'Warsaw, Krakow, Wroclaw',
        nanaNote: '"Poland\'s international school sector has grown rapidly. Warsaw has strong IB and British curriculum options."',
        imageUrl: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Germany',
        slug: 'germany',
        flagCode: 'de',
        schoolCount: 155,
        cities: 'Berlin, Munich, Hamburg',
        nanaNote: '"Strong STEM focus. Excellent university pathways to European institutions."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'France',
        slug: 'france',
        flagCode: 'fr',
        schoolCount: 110,
        cities: 'Paris, Lyon, Nice',
        nanaNote: '"Paris has a strong network of international schools. The American School of Paris is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Sweden',
        slug: 'sweden',
        flagCode: 'se',
        schoolCount: 67,
        cities: 'Stockholm, Gothenburg, Malmö',
        nanaNote: '"Sweden\'s international schools are small in number but excellent in quality. Stockholm has several strong English-medium options."',
        imageUrl: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Netherlands',
        slug: 'netherlands',
        flagCode: 'nl',
        schoolCount: 74,
        cities: 'Amsterdam, The Hague, Rotterdam',
        nanaNote: '"The Hague has a high concentration of international schools, driven by its diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Norway',
        slug: 'norway',
        flagCode: 'no',
        schoolCount: 53,
        cities: 'Oslo, Bergen',
        nanaNote: '"Oslo has a small but well-resourced international school community. Good for energy-sector expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Italy',
        slug: 'italy',
        flagCode: 'it',
        schoolCount: 68,
        cities: 'Rome, Milan, Florence',
        nanaNote: '"Culture-rich campuses. Great for arts and humanities-focused families."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Romania',
        slug: 'romania',
        flagCode: 'ro',
        schoolCount: 34,
        cities: 'Bucharest, Cluj-Napoca',
        nanaNote: '"Bucharest has a growing international school sector. Good value for European education."',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Czech Republic',
        slug: 'czech-republic',
        flagCode: 'cz',
        schoolCount: 32,
        cities: 'Prague, Brno',
        nanaNote: '"Prague is a beautiful, affordable European city with a growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Greece',
        slug: 'greece',
        flagCode: 'gr',
        schoolCount: 29,
        cities: 'Athens, Thessaloniki',
        nanaNote: '"Athens has established British and American curriculum schools. Popular with diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Portugal',
        slug: 'portugal',
        flagCode: 'pt',
        schoolCount: 24,
        cities: 'Lisbon, Porto, Cascais',
        nanaNote: '"Lisbon and Cascais have excellent international schools. A top destination for relocating families."',
        imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Austria',
        slug: 'austria',
        flagCode: 'at',
        schoolCount: 25,
        cities: 'Vienna, Salzburg',
        nanaNote: '"A hidden gem. AMADEUS International School in Vienna is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1516550893885-985c836c9b3c?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Denmark',
        slug: 'denmark',
        flagCode: 'dk',
        schoolCount: 23,
        cities: 'Copenhagen, Aarhus',
        nanaNote: '"Copenhagen International School is one of the largest and most prestigious in Scandinavia."',
        imageUrl: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Belgium',
        slug: 'belgium',
        flagCode: 'be',
        schoolCount: 22,
        cities: 'Brussels, Antwerp',
        nanaNote: '"Brussels is home to many international school options driven by the EU and NATO communities."',
        imageUrl: 'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Hungary',
        slug: 'hungary',
        flagCode: 'hu',
        schoolCount: 21,
        cities: 'Budapest',
        nanaNote: '"Budapest has a growing international school sector. Good value for Central European education."',
        imageUrl: 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Finland',
        slug: 'finland',
        flagCode: 'fi',
        schoolCount: 21,
        cities: 'Helsinki, Espoo',
        nanaNote: '"Finland\'s education system is world-renowned. Helsinki has strong international school options."',
        imageUrl: 'https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Turkey',
        slug: 'turkey',
        flagCode: 'tr',
        schoolCount: 128,
        cities: 'Istanbul, Ankara',
        nanaNote: '"Istanbul has a growing international school community with strong IB options."',
        imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ireland',
        slug: 'ireland',
        flagCode: 'ie',
        schoolCount: 18,
        cities: 'Dublin, Cork',
        nanaNote: '"English-medium, welcoming, and increasingly popular with Asian families."',
        imageUrl: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Lithuania',
        slug: 'lithuania',
        flagCode: 'lt',
        schoolCount: 13,
        cities: 'Vilnius, Kaunas',
        nanaNote: '"Vilnius has a small international school community, popular with expat and diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bulgaria',
        slug: 'bulgaria',
        flagCode: 'bg',
        schoolCount: 13,
        cities: 'Sofia, Plovdiv',
        nanaNote: '"Sofia has international schools serving the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Slovakia',
        slug: 'slovakia',
        flagCode: 'sk',
        schoolCount: 11,
        cities: 'Bratislava',
        nanaNote: '"Bratislava has a small but growing international school scene close to Vienna."',
        imageUrl: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Russia',
        slug: 'russia',
        flagCode: 'ru',
        schoolCount: 10,
        cities: 'Moscow, St Petersburg',
        nanaNote: '"Moscow has established international schools serving the expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1513326738677-b964603b136d?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Estonia',
        slug: 'estonia',
        flagCode: 'ee',
        schoolCount: 10,
        cities: 'Tallinn',
        nanaNote: '"Tallinn is one of Europe\'s most digital cities. Growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Latvia',
        slug: 'latvia',
        flagCode: 'lv',
        schoolCount: 10,
        cities: 'Riga',
        nanaNote: '"Riga has a small international school community. Good for Baltic expat postings."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cyprus',
        slug: 'cyprus',
        flagCode: 'cy',
        schoolCount: 9,
        cities: 'Nicosia, Limassol',
        nanaNote: '"Cyprus has English-medium schools and a warm climate. Popular with expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Serbia',
        slug: 'serbia',
        flagCode: 'rs',
        schoolCount: 9,
        cities: 'Belgrade',
        nanaNote: '"Belgrade has a handful of international schools serving the diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Luxembourg',
        slug: 'luxembourg',
        flagCode: 'lu',
        schoolCount: 9,
        cities: 'Luxembourg City',
        nanaNote: '"The European School Luxembourg is one of the finest multilingual schools in Europe."',
        imageUrl: 'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ukraine',
        slug: 'ukraine',
        flagCode: 'ua',
        schoolCount: 5,
        cities: 'Kyiv, Lviv',
        nanaNote: '"Kyiv had a well-established international school community prior to 2022."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Croatia',
        slug: 'croatia',
        flagCode: 'hr',
        schoolCount: 6,
        cities: 'Zagreb, Split',
        nanaNote: '"Zagreb has a small international school sector. Croatia is an increasingly popular expat destination."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Slovenia',
        slug: 'slovenia',
        flagCode: 'si',
        schoolCount: 5,
        cities: 'Ljubljana',
        nanaNote: '"Ljubljana has a small but growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'North Macedonia',
        slug: 'north-macedonia',
        flagCode: 'mk',
        schoolCount: 4,
        cities: 'Skopje',
        nanaNote: '"Skopje has a small international school community serving expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Montenegro',
        slug: 'montenegro',
        flagCode: 'me',
        schoolCount: 4,
        cities: 'Podgorica, Budva',
        nanaNote: '"A small Adriatic country with a growing expat community and international school options."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Albania',
        slug: 'albania',
        flagCode: 'al',
        schoolCount: 3,
        cities: 'Tirana',
        nanaNote: '"Tirana has a small international school community. An emerging Balkan destination."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Iceland',
        slug: 'iceland',
        flagCode: 'is',
        schoolCount: 3,
        cities: 'Reykjavik',
        nanaNote: '"Small international school community in Reykjavik. Unique environment for adventurous families."',
        imageUrl: 'https://images.unsplash.com/photo-1529963183134-61a90db47eaf?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bosnia and Herzegovina',
        slug: 'bosnia-and-herzegovina',
        flagCode: 'ba',
        schoolCount: 3,
        cities: 'Sarajevo',
        nanaNote: '"Sarajevo has international schools serving the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Monaco',
        slug: 'monaco',
        flagCode: 'mc',
        schoolCount: 3,
        cities: 'Monaco',
        nanaNote: '"The International School of Monaco is one of Europe\'s most exclusive international schools."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Malta',
        slug: 'malta',
        flagCode: 'mt',
        schoolCount: 2,
        cities: 'Valletta',
        nanaNote: '"Malta has a small international school community in a beautiful Mediterranean setting."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Andorra',
        slug: 'andorra',
        flagCode: 'ad',
        schoolCount: 1,
        cities: 'Andorra la Vella',
        nanaNote: '"Andorra has an international school offering British and French curriculum in the Pyrenees."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Kosovo',
        slug: 'kosovo',
        flagCode: 'xk',
        schoolCount: 1,
        cities: 'Pristina',
        nanaNote: '"Pristina has international schools for the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Moldova',
        slug: 'moldova',
        flagCode: 'md',
        schoolCount: 1,
        cities: 'Chisinau',
        nanaNote: '"Chisinau has a small international school community for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Guernsey',
        slug: 'guernsey',
        flagCode: 'gg',
        schoolCount: 2,
        cities: 'St. Peter Port',
        nanaNote: '"Guernsey has small international schools in a unique Channel Island setting."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Isle of Man',
        slug: 'isle-of-man',
        flagCode: 'im',
        schoolCount: 1,
        cities: 'Douglas',
        nanaNote: '"The Isle of Man has an international school for the island\'s expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Gibraltar',
        slug: 'gibraltar',
        flagCode: 'gi',
        schoolCount: 1,
        cities: 'Gibraltar',
        nanaNote: '"Gibraltar has an international school serving this small but strategically important territory."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'east-asia',
    slug: 'east-asia',
    name: 'East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=85&auto=format&fit=crop',
    description: '6 powerhouse education markets — from Hong Kong\'s British-style schools to Japan\'s disciplined international environment.',
    nanaQuoteLabel: 'Nana\'s take on East Asia',
    nanaQuote: '"Hong Kong gives you British education quality within Asia. Japan is safe, structured and increasingly international. For China, stick to the established international schools in Shanghai and Beijing."',
    nanaQuoteStrong: 'Hong Kong gives you British education quality within Asia',
    stats: { countries: 6, schools: 1150 },
    countries: [
      {
        name: 'China',
        slug: 'china',
        flagCode: 'cn',
        schoolCount: 630,
        cities: 'Shanghai, Beijing, Shenzhen',
        nanaNote: '"Large international school network in major cities. Stick to the established names."',
        imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Japan',
        slug: 'japan',
        flagCode: 'jp',
        schoolCount: 244,
        cities: 'Tokyo, Osaka, Yokohama',
        nanaNote: '"Safe, disciplined, growing international scene. My top pick in the region."',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Hong Kong',
        slug: 'hong-kong',
        flagCode: 'hk',
        schoolCount: 244,
        cities: 'Hong Kong Island, Kowloon',
        nanaNote: '"Gateway to Asia. British-style education with an Asian edge."',
        imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'South Korea',
        slug: 'south-korea',
        flagCode: 'kr',
        schoolCount: 70,
        cities: 'Seoul, Busan',
        nanaNote: '"Korea\'s international schools are small but impressive. Seoul has several strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1517154421773-0855edd8b212?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Taiwan',
        slug: 'taiwan',
        flagCode: 'tw',
        schoolCount: 32,
        cities: 'Taipei',
        nanaNote: '"Underrated destination. Safe, affordable, and a genuinely international city."',
        imageUrl: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Macao',
        slug: 'macao',
        flagCode: 'mo',
        schoolCount: 3,
        cities: 'Macao',
        nanaNote: '"Small market adjacent to Hong Kong. A handful of international school options."',
        imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'middle-east',
    slug: 'middle-east',
    name: 'Middle East',
    nameItalicPart: 'East',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85&auto=format&fit=crop',
    description: '9 countries with world-class international schools — the UAE and Qatar have invested heavily in education infrastructure.',
    nanaQuoteLabel: 'Nana\'s take on the Middle East',
    nanaQuote: '"Dubai and Abu Dhabi have genuinely excellent international schools — the facilities rival anything I have seen in Switzerland. Qatar\'s Education City is unique in the world for having top university branches on one campus."',
    nanaQuoteStrong: 'Dubai and Abu Dhabi have genuinely excellent international schools',
    stats: { countries: 9, schools: 700 },
    countries: [
      {
        name: 'United Arab Emirates',
        slug: 'uae',
        flagCode: 'ae',
        schoolCount: 256,
        cities: 'Dubai, Abu Dhabi, Sharjah',
        nanaNote: '"Outstanding facilities. GEMS, SABIS and British-style schools everywhere."',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Saudi Arabia',
        slug: 'saudi-arabia',
        flagCode: 'sa',
        schoolCount: 187,
        cities: 'Riyadh, Jeddah, Khobar',
        nanaNote: '"Expanding rapidly. Strong American and British curriculum options in major cities."',
        imageUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Qatar',
        slug: 'qatar',
        flagCode: 'qa',
        schoolCount: 150,
        cities: 'Doha, Education City',
        nanaNote: '"Education City is one of the most unique campuses in the world."',
        imageUrl: 'https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Bahrain',
        slug: 'bahrain',
        flagCode: 'bh',
        schoolCount: 42,
        cities: 'Manama',
        nanaNote: '"Small, safe, and welcoming. Good options for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1574031908-a6d98e0aad1a?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Jordan',
        slug: 'jordan',
        flagCode: 'jo',
        schoolCount: 42,
        cities: 'Amman',
        nanaNote: '"Amman has a well-established international school community. A hub for diplomatic and NGO families."',
        imageUrl: 'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Oman',
        slug: 'oman',
        flagCode: 'om',
        schoolCount: 46,
        cities: 'Muscat',
        nanaNote: '"Quiet and safe. The British School Muscat is a standout."',
        imageUrl: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Kuwait',
        slug: 'kuwait',
        flagCode: 'kw',
        schoolCount: 33,
        cities: 'Kuwait City',
        nanaNote: '"Smaller market but with some established British and American schools."',
        imageUrl: 'https://images.unsplash.com/photo-1543788060-86d18e28b530?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Lebanon',
        slug: 'lebanon',
        flagCode: 'lb',
        schoolCount: 19,
        cities: 'Beirut',
        nanaNote: '"Beirut has a long tradition of elite private schooling. The American Community School is well-regarded."',
        imageUrl: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Iraq',
        slug: 'iraq',
        flagCode: 'iq',
        schoolCount: 8,
        cities: 'Baghdad, Erbil',
        nanaNote: '"Erbil in the Kurdistan Region has a growing international school community for energy-sector families."',
        imageUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Israel',
        slug: 'israel',
        flagCode: 'il',
        schoolCount: 5,
        cities: 'Tel Aviv, Jerusalem',
        nanaNote: '"Tel Aviv has international schools serving the diplomatic and tech-sector expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Iran',
        slug: 'iran',
        flagCode: 'ir',
        schoolCount: 4,
        cities: 'Tehran',
        nanaNote: '"Tehran has a small number of international schools serving the diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Palestine',
        slug: 'palestine',
        flagCode: 'ps',
        schoolCount: 2,
        cities: 'Ramallah, Jerusalem',
        nanaNote: '"Palestine has international schools serving the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Afghanistan',
        slug: 'afghanistan',
        flagCode: 'af',
        schoolCount: 2,
        cities: 'Kabul',
        nanaNote: '"Kabul historically had international schools — very limited options currently."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'oceania',
    slug: 'oceania',
    name: 'Oceania',
    nameItalicPart: 'Oceania',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=85&auto=format&fit=crop',
    description: 'Australia and New Zealand offer world-class education in a relaxed, safe environment. Strong universities, outdoor lifestyle, and welcoming communities.',
    nanaQuoteLabel: 'Nana\'s take on Oceania',
    nanaQuote: '"Australia and New Zealand are seriously underrated as study destinations. The schools are excellent, the outdoor lifestyle is unmatched, and the universities rank among the world\'s best."',
    nanaQuoteStrong: 'Australia and New Zealand are seriously underrated',
    stats: { countries: 4, schools: 230 },
    countries: [
      {
        name: 'Australia',
        slug: 'australia',
        flagCode: 'au',
        schoolCount: 204,
        cities: 'Sydney, Melbourne, Brisbane',
        nanaNote: '"World-class universities, safe environment, strong IB and A-Level programmes."',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'New Zealand',
        slug: 'new-zealand',
        flagCode: 'nz',
        schoolCount: 20,
        cities: 'Auckland, Wellington',
        nanaNote: '"Outstanding quality of life. Auckland International College is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Fiji',
        slug: 'fiji',
        flagCode: 'fj',
        schoolCount: 2,
        cities: 'Suva, Nadi',
        nanaNote: '"A handful of international schools in Fiji, mostly serving expat and diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Papua New Guinea',
        slug: 'papua-new-guinea',
        flagCode: 'pg',
        schoolCount: 1,
        cities: 'Port Moresby',
        nanaNote: '"Port Moresby has international schools serving the mining and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'americas',
    slug: 'americas',
    name: 'Americas',
    nameItalicPart: 'Americas',
    heroImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1400&q=85&auto=format&fit=crop',
    description: 'From New England\'s elite prep schools to Canada\'s welcoming international campuses — the Americas offer a distinct education culture.',
    nanaQuoteLabel: 'Nana\'s take on the Americas',
    nanaQuote: '"US boarding schools like Exeter, Andover and Choate have a prestige all their own. Canada is an excellent alternative — strong quality, lower fees, and a welcoming immigration path."',
    nanaQuoteStrong: 'US boarding schools have a prestige all their own',
    stats: { countries: 20, schools: 600 },
    countries: [
      {
        name: 'United States',
        slug: 'usa',
        flagCode: 'us',
        schoolCount: 1532,
        cities: 'New England, New York, California',
        nanaNote: '"Ivy League pathway. Phillips Exeter, Andover, Choate — these names open every door."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Canada',
        slug: 'canada',
        flagCode: 'ca',
        schoolCount: 380,
        cities: 'Toronto, Vancouver, Montreal',
        nanaNote: '"Strong quality, welcoming to international families, excellent universities."',
        imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Mexico',
        slug: 'mexico',
        flagCode: 'mx',
        schoolCount: 145,
        cities: 'Mexico City, Monterrey',
        nanaNote: '"Strong American-curriculum schools in Mexico City for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brazil',
        slug: 'brazil',
        flagCode: 'br',
        schoolCount: 97,
        cities: 'São Paulo, Rio de Janeiro',
        nanaNote: '"São Paulo has a thriving international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ecuador',
        slug: 'ecuador',
        flagCode: 'ec',
        schoolCount: 82,
        cities: 'Quito, Guayaquil',
        nanaNote: '"Quito has a handful of strong international schools. The Cotopaxi Academy is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1484627147104-f5197bcd6651?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Peru',
        slug: 'peru',
        flagCode: 'pe',
        schoolCount: 76,
        cities: 'Lima',
        nanaNote: '"Lima\'s international schools are well-regarded. Colegio Franklin D. Roosevelt is the flagship American school."',
        imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Colombia',
        slug: 'colombia',
        flagCode: 'co',
        schoolCount: 68,
        cities: 'Bogotá, Medellín',
        nanaNote: '"Bogotá has solid bilingual international schools. A growing destination for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1533236897111-3e94666b2edf?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Argentina',
        slug: 'argentina',
        flagCode: 'ar',
        schoolCount: 68,
        cities: 'Buenos Aires',
        nanaNote: '"Buenos Aires has a long-established international school scene. Lincoln International Academy is a standout."',
        imageUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Costa Rica',
        slug: 'costa-rica',
        flagCode: 'cr',
        schoolCount: 47,
        cities: 'San José',
        nanaNote: '"A favourite for families who want English-medium schooling in a safe, nature-rich environment."',
        imageUrl: 'https://images.unsplash.com/photo-1538978500879-0caab543d71c?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Chile',
        slug: 'chile',
        flagCode: 'cl',
        schoolCount: 37,
        cities: 'Santiago',
        nanaNote: '"Santiago has well-run bilingual and IB schools. The Redland School is particularly strong."',
        imageUrl: 'https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Venezuela',
        slug: 'venezuela',
        flagCode: 've',
        schoolCount: 13,
        cities: 'Caracas',
        nanaNote: '"Caracas has established international schools serving the expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Uruguay',
        slug: 'uruguay',
        flagCode: 'uy',
        schoolCount: 8,
        cities: 'Montevideo',
        nanaNote: '"Montevideo has a small international school community. One of South America\'s safest cities."',
        imageUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bahamas',
        slug: 'bahamas',
        flagCode: 'bs',
        schoolCount: 7,
        cities: 'Nassau',
        nanaNote: '"Nassau has international schools serving the expat and financial-sector community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bermuda',
        slug: 'bermuda',
        flagCode: 'bm',
        schoolCount: 6,
        cities: 'Hamilton',
        nanaNote: '"Bermuda\'s international schools serve the financial and reinsurance sector expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bolivia',
        slug: 'bolivia',
        flagCode: 'bo',
        schoolCount: 5,
        cities: 'La Paz, Santa Cruz',
        nanaNote: '"La Paz and Santa Cruz have international schools for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cayman Islands',
        slug: 'cayman-islands',
        flagCode: 'ky',
        schoolCount: 5,
        cities: 'George Town',
        nanaNote: '"The Cayman Islands has strong international schools serving the financial community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'El Salvador',
        slug: 'el-salvador',
        flagCode: 'sv',
        schoolCount: 5,
        cities: 'San Salvador',
        nanaNote: '"San Salvador has international schools serving the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Barbados',
        slug: 'barbados',
        flagCode: 'bb',
        schoolCount: 5,
        cities: 'Bridgetown',
        nanaNote: '"Barbados has established international schools. Codrington School is the longest-running."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Dominican Republic',
        slug: 'dominican-republic',
        flagCode: 'do',
        schoolCount: 4,
        cities: 'Santo Domingo',
        nanaNote: '"Santo Domingo has international schools for the expat and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Guatemala',
        slug: 'guatemala',
        flagCode: 'gt',
        schoolCount: 4,
        cities: 'Guatemala City',
        nanaNote: '"Guatemala City has international schools for expat and diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Panama',
        slug: 'panama',
        flagCode: 'pa',
        schoolCount: 3,
        cities: 'Panama City',
        nanaNote: '"Panama City has international schools serving the expat and logistics community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Nicaragua',
        slug: 'nicaragua',
        flagCode: 'ni',
        schoolCount: 3,
        cities: 'Managua',
        nanaNote: '"Managua has a small number of international schools for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Trinidad and Tobago',
        slug: 'trinidad-and-tobago',
        flagCode: 'tt',
        schoolCount: 3,
        cities: 'Port of Spain',
        nanaNote: '"Port of Spain has international schools serving the energy-sector expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Puerto Rico',
        slug: 'puerto-rico',
        flagCode: 'pr',
        schoolCount: 3,
        cities: 'San Juan',
        nanaNote: '"San Juan has international schools with a bilingual Spanish-English focus."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Honduras',
        slug: 'honduras',
        flagCode: 'hn',
        schoolCount: 2,
        cities: 'Tegucigalpa',
        nanaNote: '"Tegucigalpa has international schools for expat and diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Jamaica',
        slug: 'jamaica',
        flagCode: 'jm',
        schoolCount: 2,
        cities: 'Kingston',
        nanaNote: '"Kingston has international schools serving the diplomatic and business community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Paraguay',
        slug: 'paraguay',
        flagCode: 'py',
        schoolCount: 2,
        cities: 'Asuncion',
        nanaNote: '"Asuncion has international schools for the expat and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cuba',
        slug: 'cuba',
        flagCode: 'cu',
        schoolCount: 1,
        cities: 'Havana',
        nanaNote: '"Havana has an international school serving the diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Curaçao',
        slug: 'curacao',
        flagCode: 'cw',
        schoolCount: 2,
        cities: 'Willemstad',
        nanaNote: '"Willemstad has an international school serving this Dutch Caribbean island community."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Anguilla',
        slug: 'anguilla',
        flagCode: 'ai',
        schoolCount: 1,
        cities: 'The Valley',
        nanaNote: '"Anguilla has a small international school for this exclusive Caribbean territory."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'British Virgin Islands',
        slug: 'british-virgin-islands',
        flagCode: 'vg',
        schoolCount: 1,
        cities: 'Road Town',
        nanaNote: '"The BVI has a small international school community in a beautiful island setting."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Sint Maarten',
        slug: 'sint-maarten',
        flagCode: 'sx',
        schoolCount: 1,
        cities: 'Philipsburg',
        nanaNote: '"Sint Maarten has a small international school on this Dutch-side Caribbean island."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'United States Virgin Islands',
        slug: 'united-states-virgin-islands',
        flagCode: 'vi',
        schoolCount: 1,
        cities: 'Charlotte Amalie',
        nanaNote: '"The US Virgin Islands has a small international school on St. Thomas."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'south-asia',
    slug: 'south-asia',
    name: 'South Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1400&q=85&auto=format&fit=crop',
    description: 'India leads South Asia with a rapidly growing international school sector. Strong academic culture, competitive fees, and increasingly strong university pathways.',
    nanaQuoteLabel: 'Nana\'s take on South Asia',
    nanaQuote: '"India\'s international school sector has grown enormously. Mumbai, Bangalore and Delhi all have strong options. Sri Lanka is a lovely, safe choice for families who want a quieter pace."',
    nanaQuoteStrong: 'India\'s international school sector has grown enormously',
    stats: { countries: 5, schools: 590 },
    countries: [
      {
        name: 'India',
        slug: 'india',
        flagCode: 'in',
        schoolCount: 534,
        cities: 'Mumbai, Bangalore, Delhi',
        nanaNote: '"Strong growth in IB schools. Pathways Learning Academy and Oberoi International are standouts."',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Pakistan',
        slug: 'pakistan',
        flagCode: 'pk',
        schoolCount: 36,
        cities: 'Karachi, Lahore, Islamabad',
        nanaNote: '"British curriculum schools in major cities. Beaconhouse is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Nepal',
        slug: 'nepal',
        flagCode: 'np',
        schoolCount: 9,
        cities: 'Kathmandu',
        nanaNote: '"Kathmandu has a small international school community. Lincoln School is the most established."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Sri Lanka',
        slug: 'sri-lanka',
        flagCode: 'lk',
        schoolCount: 7,
        cities: 'Colombo',
        nanaNote: '"Affordable, safe, and English-medium. Good for families who value a calmer pace."',
        imageUrl: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bangladesh',
        slug: 'bangladesh',
        flagCode: 'bd',
        schoolCount: 5,
        cities: 'Dhaka',
        nanaNote: '"Growing international community in Dhaka. Good for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1555990793-da11153b6ec9?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'africa',
    slug: 'africa',
    name: 'Africa',
    nameItalicPart: 'Africa',
    heroImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=85&auto=format&fit=crop',
    description: 'Africa\'s international school sector spans 20+ countries — anchored by Kenya, Egypt, Nigeria and South Africa with long-established British and American curriculum schools.',
    nanaQuoteLabel: 'Nana\'s take on Africa',
    nanaQuote: '"Nairobi is one of the most underrated international school cities in the world. The Aga Khan Academy and Brookhouse School are genuinely world-class. South Africa has strong British-style schools with excellent outdoor programmes."',
    nanaQuoteStrong: 'Nairobi is one of the most underrated international school cities',
    stats: { countries: 22, schools: 400 },
    countries: [
      {
        name: 'Egypt',
        slug: 'egypt',
        flagCode: 'eg',
        schoolCount: 97,
        cities: 'Cairo, Alexandria',
        nanaNote: '"Cairo has a large, well-established international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Kenya',
        slug: 'kenya',
        flagCode: 'ke',
        schoolCount: 66,
        cities: 'Nairobi, Mombasa',
        nanaNote: '"Nairobi\'s international school scene is world-class. Aga Khan Academy is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Nigeria',
        slug: 'nigeria',
        flagCode: 'ng',
        schoolCount: 59,
        cities: 'Lagos, Abuja',
        nanaNote: '"Lagos is West Africa\'s education hub. Several strong British-curriculum schools."',
        imageUrl: 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Morocco',
        slug: 'morocco',
        flagCode: 'ma',
        schoolCount: 27,
        cities: 'Casablanca, Rabat',
        nanaNote: '"Casablanca has well-established French and British curriculum schools."',
        imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Uganda',
        slug: 'uganda',
        flagCode: 'ug',
        schoolCount: 23,
        cities: 'Kampala',
        nanaNote: '"Kampala has a small but growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Tanzania',
        slug: 'tanzania',
        flagCode: 'tz',
        schoolCount: 18,
        cities: 'Dar es Salaam, Arusha',
        nanaNote: '"International schools in Dar es Salaam are strong and well-resourced."',
        imageUrl: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ghana',
        slug: 'ghana',
        flagCode: 'gh',
        schoolCount: 13,
        cities: 'Accra',
        nanaNote: '"Accra has a small but well-regarded international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1578328819058-a6d93bb26285?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cameroon',
        slug: 'cameroon',
        flagCode: 'cm',
        schoolCount: 7,
        cities: 'Yaoundé, Douala',
        nanaNote: '"Yaoundé has international schools serving the diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Mauritius',
        slug: 'mauritius',
        flagCode: 'mu',
        schoolCount: 7,
        cities: 'Port Louis',
        nanaNote: '"Mauritius has a growing international school sector. Popular with families relocating from Europe."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ethiopia',
        slug: 'ethiopia',
        flagCode: 'et',
        schoolCount: 8,
        cities: 'Addis Ababa',
        nanaNote: '"Addis Ababa is Africa\'s diplomatic hub. The International Community School is the top choice."',
        imageUrl: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'South Africa',
        slug: 'south-africa',
        flagCode: 'za',
        schoolCount: 5,
        cities: 'Cape Town, Johannesburg',
        nanaNote: '"British-style schools with excellent outdoor programmes and stunning campuses."',
        imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Zambia',
        slug: 'zambia',
        flagCode: 'zm',
        schoolCount: 6,
        cities: 'Lusaka',
        nanaNote: '"Lusaka has British-curriculum schools serving the expat and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Rwanda',
        slug: 'rwanda',
        flagCode: 'rw',
        schoolCount: 5,
        cities: 'Kigali',
        nanaNote: '"Kigali is clean, safe, and increasingly international. A surprising gem for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Tunisia',
        slug: 'tunisia',
        flagCode: 'tn',
        schoolCount: 4,
        cities: 'Tunis',
        nanaNote: '"Tunis has international schools serving the diplomatic and expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Gabon',
        slug: 'gabon',
        flagCode: 'ga',
        schoolCount: 4,
        cities: 'Libreville',
        nanaNote: '"Libreville has international schools serving the oil-sector expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Botswana',
        slug: 'botswana',
        flagCode: 'bw',
        schoolCount: 4,
        cities: 'Gaborone',
        nanaNote: '"Gaborone has international schools for the diamond-sector and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Mozambique',
        slug: 'mozambique',
        flagCode: 'mz',
        schoolCount: 4,
        cities: 'Maputo',
        nanaNote: '"Maputo has international schools for the energy-sector and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Senegal',
        slug: 'senegal',
        flagCode: 'sn',
        schoolCount: 4,
        cities: 'Dakar',
        nanaNote: '"Dakar has well-established French-medium and international schools."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Angola',
        slug: 'angola',
        flagCode: 'ao',
        schoolCount: 3,
        cities: 'Luanda',
        nanaNote: '"Luanda has international schools serving the oil-sector expat community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Togo',
        slug: 'togo',
        flagCode: 'tg',
        schoolCount: 3,
        cities: 'Lomé',
        nanaNote: '"Lomé has a small international school community for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Namibia',
        slug: 'namibia',
        flagCode: 'na',
        schoolCount: 3,
        cities: 'Windhoek',
        nanaNote: '"Windhoek has international schools with a strong British curriculum tradition."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Malawi',
        slug: 'malawi',
        flagCode: 'mw',
        schoolCount: 3,
        cities: 'Lilongwe, Blantyre',
        nanaNote: '"Malawi has a small international school community for NGO and expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ivory Coast',
        slug: 'ivory-coast',
        flagCode: 'ci',
        schoolCount: 2,
        cities: 'Abidjan',
        nanaNote: '"Abidjan has international schools for the West African business and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Madagascar',
        slug: 'madagascar',
        flagCode: 'mg',
        schoolCount: 2,
        cities: 'Antananarivo',
        nanaNote: '"Antananarivo has small international schools for the expat and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Sudan',
        slug: 'sudan',
        flagCode: 'sd',
        schoolCount: 2,
        cities: 'Khartoum',
        nanaNote: '"Khartoum historically had international schools — very limited options currently."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Gambia',
        slug: 'gambia',
        flagCode: 'gm',
        schoolCount: 2,
        cities: 'Banjul',
        nanaNote: '"Banjul has a small international school community in West Africa\'s smallest country."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Zimbabwe',
        slug: 'zimbabwe',
        flagCode: 'zw',
        schoolCount: 1,
        cities: 'Harare',
        nanaNote: '"Harare has a small international school community. Peterhouse and St. George\'s are well-regarded."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Eswatini',
        slug: 'eswatini',
        flagCode: 'sz',
        schoolCount: 1,
        cities: 'Mbabane',
        nanaNote: '"Eswatini has a small international school for expat families in this small Southern African kingdom."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Lesotho',
        slug: 'lesotho',
        flagCode: 'ls',
        schoolCount: 1,
        cities: 'Maseru',
        nanaNote: '"Maseru has a small international school serving the NGO and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Seychelles',
        slug: 'seychelles',
        flagCode: 'sc',
        schoolCount: 1,
        cities: 'Victoria',
        nanaNote: '"The Seychelles has an international school on Mahé island — a true tropical setting."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Sierra Leone',
        slug: 'sierra-leone',
        flagCode: 'sl',
        schoolCount: 1,
        cities: 'Freetown',
        nanaNote: '"Freetown has international schools for the diplomatic and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'central-asia',
    slug: 'central-asia',
    name: 'Central Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1400&q=85&auto=format&fit=crop',
    description: 'A rapidly developing region — Kazakhstan and Uzbekistan are investing heavily in international education infrastructure, while the Caucasus nations offer smaller but established markets.',
    nanaQuoteLabel: 'Nana\'s take on Central Asia',
    nanaQuote: '"Kazakhstan is the standout in this region. Nur-Sultan and Almaty have some genuinely impressive international schools — well-resourced, ambitious and growing fast. Georgia and Armenia are quieter gems for families who want European-style education at affordable fees."',
    nanaQuoteStrong: 'Kazakhstan is the standout in this region',
    stats: { countries: 6, schools: 135 },
    countries: [
      {
        name: 'Kazakhstan',
        slug: 'kazakhstan',
        flagCode: 'kz',
        schoolCount: 72,
        cities: 'Almaty, Astana',
        nanaNote: '"Kazakhstan\'s international school sector is one of the fastest-growing in the world. Haileybury Almaty is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Uzbekistan',
        slug: 'uzbekistan',
        flagCode: 'uz',
        schoolCount: 21,
        cities: 'Tashkent, Samarkand',
        nanaNote: '"Tashkent has a growing international school sector. Westminster International University is a regional standout."',
        imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Azerbaijan',
        slug: 'azerbaijan',
        flagCode: 'az',
        schoolCount: 19,
        cities: 'Baku',
        nanaNote: '"Baku has established international schools driven by the oil sector. QSI Baku is well-regarded."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Georgia',
        slug: 'georgia',
        flagCode: 'ge',
        schoolCount: 9,
        cities: 'Tbilisi',
        nanaNote: '"Tbilisi has a charming international school community. European-feel with affordable fees."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Armenia',
        slug: 'armenia',
        flagCode: 'am',
        schoolCount: 6,
        cities: 'Yerevan',
        nanaNote: '"Yerevan has a small international school community with strong IB options."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Mongolia',
        slug: 'mongolia',
        flagCode: 'mn',
        schoolCount: 5,
        cities: 'Ulaanbaatar',
        nanaNote: '"Ulaanbaatar has international schools for the mining-sector and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Kyrgyzstan',
        slug: 'kyrgyzstan',
        flagCode: 'kg',
        schoolCount: 1,
        cities: 'Bishkek',
        nanaNote: '"Bishkek has a small international school for the expat and diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Tajikistan',
        slug: 'tajikistan',
        flagCode: 'tj',
        schoolCount: 1,
        cities: 'Dushanbe',
        nanaNote: '"Dushanbe has a small international school community for expat and diplomatic families."',
        imageUrl: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
]

export function getRegionData(slug: string): RegionData | undefined {
  return REGIONS_DATA.find(r => r.slug === slug)
}
