export interface RegionCountry {
  name: string
  slug: string
  flagCode: string
  schoolCount: number
  cities: string
  nanaNote: string
  imageUrl: string
  isFeatured?: boolean
  hasVisitedRibbon?: boolean
}

export interface RegionData {
  id: string
  slug: string
  name: string
  nameItalicPart: string
  heroImage: string
  description: string
  nanaQuoteLabel: string
  nanaQuote: string
  nanaQuoteStrong: string
  stats: {
    countries: number
    schools: number
  }
  countries: RegionCountry[]
}

export const ALL_REGION_STUBS = [
  { slug: 'southeast-asia', name: 'South East Asia', sub: '9 countries', count: 1017 },
  { slug: 'europe', name: 'Europe', sub: '35 countries incl. UK', count: 1347 },
  { slug: 'middle-east', name: 'Middle East', sub: 'UAE, Qatar, KSA', count: 776 },
  { slug: 'east-asia', name: 'East Asia', sub: 'China, Japan, HK, Korea', count: 583 },
  { slug: 'oceania', name: 'Oceania', sub: 'Australia, New Zealand', count: 93 },
  { slug: 'americas', name: 'Americas', sub: 'USA, Canada + 27 more', count: 887 },
  { slug: 'south-asia', name: 'South Asia', sub: 'India, Pakistan + more', count: 234 },
  { slug: 'africa', name: 'Africa', sub: 'Kenya, Egypt, South Africa', count: 499 },
]

export const REGIONS_DATA: RegionData[] = [
  {
    id: 'southeast-asia',
    slug: 'southeast-asia',
    name: 'South East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1400&q=85&auto=format&fit=crop',
    description: '9 countries across the region — from Singapore\'s world-class international campuses to Thailand\'s fast-growing local schools. Nana knows each market personally.',
    nanaQuoteLabel: 'Nana\'s take on South East Asia',
    nanaQuote: '"For families considering staying in Asia, Singapore is my first recommendation for a truly world-class English-medium education. Malaysia is excellent value — Marlborough Malaysia is a fraction of UK fees. And Thailand itself has strong international schools in Bangkok, Chiang Mai and Phuket. Start with the country that fits your family\'s lifestyle."',
    nanaQuoteStrong: 'Singapore is my first recommendation',
    stats: { countries: 9, schools: 1017 },
    countries: [
      {
        name: 'Thailand',
        slug: 'thailand',
        flagCode: 'th',
        schoolCount: 171,
        cities: 'Bangkok, Chiang Mai, Phuket',
        nanaNote: '"Excellent value international community. Bangkok, Chiang Mai and Phuket all have strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Singapore',
        slug: 'singapore',
        flagCode: 'sg',
        schoolCount: 112,
        cities: 'City-state',
        nanaNote: '"World-class options. Strong British curriculum — best outside the UK."',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Malaysia',
        slug: 'malaysia',
        flagCode: 'my',
        schoolCount: 20,
        cities: 'Kuala Lumpur, Penang',
        nanaNote: '"Marlborough Malaysia is excellent value — a fraction of UK fees."',
        imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Vietnam',
        slug: 'vietnam',
        flagCode: 'vn',
        schoolCount: 18,
        cities: 'Ho Chi Minh City, Hanoi',
        nanaNote: '"Fast-growing expat scene. Good IB options in Ho Chi Minh City."',
        imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Indonesia',
        slug: 'indonesia',
        flagCode: 'id',
        schoolCount: 20,
        cities: 'Jakarta, Bali',
        nanaNote: '"Strong choices in Jakarta. BIS and SIS are both solid."',
        imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Philippines',
        slug: 'philippines',
        flagCode: 'ph',
        schoolCount: 20,
        cities: 'Manila, Cebu',
        nanaNote: '"Good English-medium options. Less formal boarding culture."',
        imageUrl: 'https://images.unsplash.com/photo-1546542476-4d68dc7cd012?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Myanmar',
        slug: 'myanmar',
        flagCode: 'mm',
        schoolCount: 7,
        cities: 'Yangon',
        nanaNote: '"Yangon has a small but quality international community."',
        imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cambodia',
        slug: 'cambodia',
        flagCode: 'kh',
        schoolCount: 5,
        cities: 'Phnom Penh',
        nanaNote: '"Smaller market but improving. Good for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'europe',
    slug: 'europe',
    name: 'Europe',
    nameItalicPart: 'Europe',
    heroImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1400&q=85&auto=format&fit=crop',
    description: '35 countries with over 1,300 international schools — from Britain\'s centuries-old boarding tradition to Switzerland\'s elite alpine campuses. The gold standard of international education.',
    nanaQuoteLabel: 'Nana\'s take on Europe',
    nanaQuote: '"For families who want the very best boarding education, Europe is unbeatable. The UK has boarding schools for every personality. Switzerland offers a unique multilingual environment with stunning campuses. Both are worth the investment if your child is ready for boarding life."',
    nanaQuoteStrong: 'Europe is unbeatable',
    stats: { countries: 35, schools: 1347 },
    countries: [
      {
        name: 'United Kingdom',
        slug: 'united-kingdom',
        flagCode: 'gb',
        schoolCount: 52,
        cities: 'London, Surrey, Berkshire',
        nanaNote: '"Top boarding tradition. Strong IB and A-Levels. I have visited every school personally."',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
        hasVisitedRibbon: true,
      },
      {
        name: 'Switzerland',
        slug: 'switzerland',
        flagCode: 'ch',
        schoolCount: 109,
        cities: 'Lausanne, Montreux, Leysin',
        nanaNote: '"Premium boarding, multilingual, stunning alpine campuses. Worth every franc."',
        imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Italy',
        slug: 'italy',
        flagCode: 'it',
        schoolCount: 7,
        cities: 'Rome, Milan, Florence',
        nanaNote: '"Culture-rich campuses. Great for arts and humanities-focused families."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Germany',
        slug: 'germany',
        flagCode: 'de',
        schoolCount: 3,
        cities: 'Berlin, Munich, Hamburg',
        nanaNote: '"Strong STEM focus. Excellent university pathways to European institutions."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Austria',
        slug: 'austria',
        flagCode: 'at',
        schoolCount: 1,
        cities: 'Vienna, Salzburg',
        nanaNote: '"A hidden gem. AMADEUS International School in Vienna is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1516550893885-985c836c9b3c?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'east-asia',
    slug: 'east-asia',
    name: 'East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=85&auto=format&fit=crop',
    description: '5 powerhouse education markets — from Hong Kong\'s British-style schools to Japan\'s disciplined international environment. China\'s international school scene has grown remarkably in major cities.',
    nanaQuoteLabel: 'Nana\'s take on East Asia',
    nanaQuote: '"Hong Kong gives you British education quality within Asia — ideal for families who want the best of both worlds. Japan is safe, structured and increasingly international. For China, stick to the established international schools in Shanghai and Beijing."',
    nanaQuoteStrong: 'Hong Kong gives you British education quality within Asia',
    stats: { countries: 5, schools: 583 },
    countries: [
      {
        name: 'China',
        slug: 'china',
        flagCode: 'cn',
        schoolCount: 165,
        cities: 'Shanghai, Beijing, Shenzhen',
        nanaNote: '"Large international school network in major cities. Stick to the established names."',
        imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Hong Kong',
        slug: 'hong-kong',
        flagCode: 'hk',
        schoolCount: 134,
        cities: 'Hong Kong Island, Kowloon',
        nanaNote: '"Gateway to Asia. British-style education with an Asian edge."',
        imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Japan',
        slug: 'japan',
        flagCode: 'jp',
        schoolCount: 107,
        cities: 'Tokyo, Osaka, Yokohama',
        nanaNote: '"Safe, disciplined, growing international scene. My top pick in the region."',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Taiwan',
        slug: 'taiwan',
        flagCode: 'tw',
        schoolCount: 20,
        cities: 'Taipei',
        nanaNote: '"Underrated destination. Safe, affordable, and a genuinely international city."',
        imageUrl: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'South Korea',
        slug: 'south-korea',
        flagCode: 'kr',
        schoolCount: 20,
        cities: 'Seoul, Busan',
        nanaNote: '"Korea\'s international schools are small but impressive. Seoul has several strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1517154421773-0855edd8b212?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'middle-east',
    slug: 'middle-east',
    name: 'Middle East',
    nameItalicPart: 'East',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85&auto=format&fit=crop',
    description: '8 countries with world-class international schools — the UAE and Qatar have invested heavily in education infrastructure. Excellent facilities, competitive fees, and strong university outcomes.',
    nanaQuoteLabel: 'Nana\'s take on the Middle East',
    nanaQuote: '"Dubai and Abu Dhabi have genuinely excellent international schools — the facilities rival anything I have seen in Switzerland. GEMS Education runs many strong campuses across the region. Qatar\'s Education City is unique in the world for having top university branches on one campus."',
    nanaQuoteStrong: 'Dubai and Abu Dhabi have genuinely excellent international schools',
    stats: { countries: 8, schools: 776 },
    countries: [
      {
        name: 'United Arab Emirates',
        slug: 'uae',
        flagCode: 'ae',
        schoolCount: 320,
        cities: 'Dubai, Abu Dhabi, Sharjah',
        nanaNote: '"Outstanding facilities. GEMS, SABIS and British-style schools everywhere."',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Qatar',
        slug: 'qatar',
        flagCode: 'qa',
        schoolCount: 120,
        cities: 'Doha, Education City',
        nanaNote: '"Education City is one of the most unique campuses in the world."',
        imageUrl: 'https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Saudi Arabia',
        slug: 'saudi-arabia',
        flagCode: 'sa',
        schoolCount: 180,
        cities: 'Riyadh, Jeddah, Khobar',
        nanaNote: '"Expanding rapidly. Strong American and British curriculum options in major cities."',
        imageUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Kuwait',
        slug: 'kuwait',
        flagCode: 'kw',
        schoolCount: 60,
        cities: 'Kuwait City',
        nanaNote: '"Smaller market but with some established British and American schools."',
        imageUrl: 'https://images.unsplash.com/photo-1543788060-86d18e28b530?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bahrain',
        slug: 'bahrain',
        flagCode: 'bh',
        schoolCount: 40,
        cities: 'Manama',
        nanaNote: '"Small, safe, and welcoming. Good options for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1574031908-a6d98e0aad1a?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Oman',
        slug: 'oman',
        flagCode: 'om',
        schoolCount: 35,
        cities: 'Muscat',
        nanaNote: '"Quiet and safe. The British School Muscat is a standout."',
        imageUrl: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'oceania',
    slug: 'oceania',
    name: 'Oceania',
    nameItalicPart: 'Oceania',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=85&auto=format&fit=crop',
    description: 'Australia and New Zealand offer world-class education in a relaxed, safe environment. Strong universities, outdoor lifestyle, and welcoming communities for international families.',
    nanaQuoteLabel: 'Nana\'s take on Oceania',
    nanaQuote: '"Australia and New Zealand are seriously underrated as study destinations. The schools are excellent, the outdoor lifestyle is unmatched, and the universities rank among the world\'s best. Sydney and Melbourne both have strong international school networks."',
    nanaQuoteStrong: 'Australia and New Zealand are seriously underrated',
    stats: { countries: 2, schools: 93 },
    countries: [
      {
        name: 'Australia',
        slug: 'australia',
        flagCode: 'au',
        schoolCount: 75,
        cities: 'Sydney, Melbourne, Brisbane',
        nanaNote: '"World-class universities, safe environment, strong IB and A-Level programmes."',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'New Zealand',
        slug: 'new-zealand',
        flagCode: 'nz',
        schoolCount: 18,
        cities: 'Auckland, Wellington',
        nanaNote: '"Outstanding quality of life. Auckland International College is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
    ],
  },
  {
    id: 'americas',
    slug: 'americas',
    name: 'Americas',
    nameItalicPart: 'Americas',
    heroImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1400&q=85&auto=format&fit=crop',
    description: 'From New England\'s elite prep schools to Canada\'s welcoming international campuses — the Americas offer a distinct education culture. US boarding schools are among the most prestigious in the world.',
    nanaQuoteLabel: 'Nana\'s take on the Americas',
    nanaQuote: '"US boarding schools like Exeter, Andover and Choate have a prestige all their own. If your child wants to attend an Ivy League university, an American prep school gives a real advantage. Canada is an excellent alternative — strong quality, lower fees, and a welcoming immigration path."',
    nanaQuoteStrong: 'US boarding schools have a prestige all their own',
    stats: { countries: 29, schools: 887 },
    countries: [
      {
        name: 'United States',
        slug: 'usa',
        flagCode: 'us',
        schoolCount: 520,
        cities: 'New England, New York, California',
        nanaNote: '"Ivy League pathway. Phillips Exeter, Andover, Choate — these names open every door."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Canada',
        slug: 'canada',
        flagCode: 'ca',
        schoolCount: 220,
        cities: 'Toronto, Vancouver, Montreal',
        nanaNote: '"Strong quality, welcoming to international families, excellent universities."',
        imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Mexico',
        slug: 'mexico',
        flagCode: 'mx',
        schoolCount: 55,
        cities: 'Mexico City, Monterrey',
        nanaNote: '"Strong American-curriculum schools in Mexico City for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brazil',
        slug: 'brazil',
        flagCode: 'br',
        schoolCount: 45,
        cities: 'São Paulo, Rio de Janeiro',
        nanaNote: '"São Paulo has a thriving international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'south-asia',
    slug: 'south-asia',
    name: 'South Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1400&q=85&auto=format&fit=crop',
    description: 'India leads South Asia with a rapidly growing international school sector in major cities. Strong academic culture, competitive fees, and increasingly strong university pathways.',
    nanaQuoteLabel: 'Nana\'s take on South Asia',
    nanaQuote: '"India\'s international school sector has grown enormously. Mumbai, Bangalore and Delhi all have strong options. Sri Lanka is a lovely, safe choice for families who want a quieter pace. The region is seriously underrated for quality and value."',
    nanaQuoteStrong: 'India\'s international school sector has grown enormously',
    stats: { countries: 4, schools: 234 },
    countries: [
      {
        name: 'India',
        slug: 'india',
        flagCode: 'in',
        schoolCount: 165,
        cities: 'Mumbai, Bangalore, Delhi',
        nanaNote: '"Strong growth in IB schools. Pathways Learning Academy and Oberoi International are standouts."',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Sri Lanka',
        slug: 'sri-lanka',
        flagCode: 'lk',
        schoolCount: 30,
        cities: 'Colombo',
        nanaNote: '"Affordable, safe, and English-medium. Good for families who value a calmer pace."',
        imageUrl: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Pakistan',
        slug: 'pakistan',
        flagCode: 'pk',
        schoolCount: 25,
        cities: 'Karachi, Lahore, Islamabad',
        nanaNote: '"British curriculum schools in major cities. Beaconhouse is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bangladesh',
        slug: 'bangladesh',
        flagCode: 'bd',
        schoolCount: 14,
        cities: 'Dhaka',
        nanaNote: '"Growing international community in Dhaka. Good for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1555990793-da11153b6ec9?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'africa',
    slug: 'africa',
    name: 'Africa',
    nameItalicPart: 'Africa',
    heroImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=85&auto=format&fit=crop',
    description: 'Africa\'s international school sector is anchored by Kenya, Egypt and South Africa — three markets with long-established British and American curriculum schools.',
    nanaQuoteLabel: 'Nana\'s take on Africa',
    nanaQuote: '"Nairobi is one of the most underrated international school cities in the world. The Aga Khan Academy and Brookhouse School are genuinely world-class. South Africa has strong British-style schools with excellent outdoor programmes."',
    nanaQuoteStrong: 'Nairobi is one of the most underrated international school cities',
    stats: { countries: 10, schools: 499 },
    countries: [
      {
        name: 'Kenya',
        slug: 'kenya',
        flagCode: 'ke',
        schoolCount: 85,
        cities: 'Nairobi, Mombasa',
        nanaNote: '"Nairobi\'s international school scene is world-class. Aga Khan Academy is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Egypt',
        slug: 'egypt',
        flagCode: 'eg',
        schoolCount: 120,
        cities: 'Cairo, Alexandria',
        nanaNote: '"Cairo has a large, well-established international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'South Africa',
        slug: 'south-africa',
        flagCode: 'za',
        schoolCount: 95,
        cities: 'Cape Town, Johannesburg',
        nanaNote: '"British-style schools with excellent outdoor programmes and stunning campuses."',
        imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Nigeria',
        slug: 'nigeria',
        flagCode: 'ng',
        schoolCount: 75,
        cities: 'Lagos, Abuja',
        nanaNote: '"Lagos is West Africa\'s education hub. Several strong British-curriculum schools."',
        imageUrl: 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Tanzania',
        slug: 'tanzania',
        flagCode: 'tz',
        schoolCount: 45,
        cities: 'Dar es Salaam, Arusha',
        nanaNote: '"International schools in Dar es Salaam are strong and well-resourced."',
        imageUrl: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
]

export function getRegionData(slug: string): RegionData | undefined {
  return REGIONS_DATA.find(r => r.slug === slug)
}
