export interface RegionCountry {
  name: string
  slug: string
  flagCode: string
  schoolCount: number
  cities: string
  nanaNote: string
  imageUrl: string
  isFeatured?: boolean
  hasVisitedRibbon?: boolean
}

export interface RegionData {
  id: string
  slug: string
  name: string
  nameItalicPart: string
  heroImage: string
  description: string
  nanaQuoteLabel: string
  nanaQuote: string
  nanaQuoteStrong: string
  stats: {
    countries: number
    schools: number
  }
  countries: RegionCountry[]
}

export const ALL_REGION_STUBS = [
  { slug: 'southeast-asia', name: 'South East Asia', sub: '9 countries', count: 676 },
  { slug: 'europe', name: 'Europe', sub: 'incl. UK, Spain, Switzerland', count: 1264 },
  { slug: 'middle-east', name: 'Middle East', sub: 'UAE, Qatar, KSA', count: 448 },
  { slug: 'east-asia', name: 'East Asia', sub: 'China, Japan, HK, Korea', count: 955 },
  { slug: 'oceania', name: 'Oceania', sub: 'Australia, New Zealand', count: 21 },
  { slug: 'americas', name: 'Americas', sub: 'USA, Canada + more', count: 192 },
  { slug: 'south-asia', name: 'South Asia', sub: 'India, Pakistan + more', count: 446 },
  { slug: 'africa', name: 'Africa', sub: 'Kenya, Egypt, Nigeria', count: 144 },
]

export const REGIONS_DATA: RegionData[] = [
  {
    id: 'southeast-asia',
    slug: 'southeast-asia',
    name: 'South East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1400&q=85&auto=format&fit=crop',
    description: '9 countries across the region — from Singapore\'s world-class international campuses to Thailand\'s fast-growing local schools. Nana knows each market personally.',
    nanaQuoteLabel: 'Nana\'s take on South East Asia',
    nanaQuote: '"For families considering staying in Asia, Singapore is my first recommendation for a truly world-class English-medium education. Malaysia is excellent value — Marlborough Malaysia is a fraction of UK fees. And Thailand itself has strong international schools in Bangkok, Chiang Mai and Phuket. Start with the country that fits your family\'s lifestyle."',
    nanaQuoteStrong: 'Singapore is my first recommendation',
    stats: { countries: 9, schools: 676 },
    countries: [
      {
        name: 'Thailand',
        slug: 'thailand',
        flagCode: 'th',
        schoolCount: 237,
        cities: 'Bangkok, Chiang Mai, Phuket',
        nanaNote: '"Excellent value international community. Bangkok, Chiang Mai and Phuket all have strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Singapore',
        slug: 'singapore',
        flagCode: 'sg',
        schoolCount: 156,
        cities: 'City-state',
        nanaNote: '"World-class options. Strong British curriculum — best outside the UK."',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Indonesia',
        slug: 'indonesia',
        flagCode: 'id',
        schoolCount: 118,
        cities: 'Jakarta, Bali',
        nanaNote: '"Strong choices in Jakarta. BIS and SIS are both solid."',
        imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Malaysia',
        slug: 'malaysia',
        flagCode: 'my',
        schoolCount: 107,
        cities: 'Kuala Lumpur, Penang',
        nanaNote: '"Marlborough Malaysia is excellent value — a fraction of UK fees."',
        imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Philippines',
        slug: 'philippines',
        flagCode: 'ph',
        schoolCount: 20,
        cities: 'Manila, Cebu',
        nanaNote: '"English-medium and affordable. Manila has a growing international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Vietnam',
        slug: 'vietnam',
        flagCode: 'vn',
        schoolCount: 15,
        cities: 'Ho Chi Minh City, Hanoi',
        nanaNote: '"Fast-growing expat scene. Good IB options in Ho Chi Minh City."',
        imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brunei',
        slug: 'brunei',
        flagCode: 'bn',
        schoolCount: 9,
        cities: 'Bandar Seri Begawan',
        nanaNote: '"Small but well-resourced market. Excellent for families in the energy sector."',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Myanmar',
        slug: 'myanmar',
        flagCode: 'mm',
        schoolCount: 8,
        cities: 'Yangon',
        nanaNote: '"A handful of solid international schools in Yangon for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Cambodia',
        slug: 'cambodia',
        flagCode: 'kh',
        schoolCount: 6,
        cities: 'Phnom Penh',
        nanaNote: '"Phnom Penh has a growing international school scene for NGO and expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1538193268820-b27e6a71a4ff?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'europe',
    slug: 'europe',
    name: 'Europe',
    nameItalicPart: 'Europe',
    heroImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1400&q=85&auto=format&fit=crop',
    description: '35 countries with over 1,300 international schools — from Britain\'s centuries-old boarding tradition to Switzerland\'s elite alpine campuses. The gold standard of international education.',
    nanaQuoteLabel: 'Nana\'s take on Europe',
    nanaQuote: '"For families who want the very best boarding education, Europe is unbeatable. The UK has boarding schools for every personality. Switzerland offers a unique multilingual environment with stunning campuses. Both are worth the investment if your child is ready for boarding life."',
    nanaQuoteStrong: 'Europe is unbeatable',
    stats: { countries: 10, schools: 1264 },
    countries: [
      {
        name: 'United Kingdom',
        slug: 'united-kingdom',
        flagCode: 'gb',
        schoolCount: 513,
        cities: 'London, Surrey, Berkshire',
        nanaNote: '"Top boarding tradition. Strong IB and A-Levels. I have visited every school personally."',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
        hasVisitedRibbon: true,
      },
      {
        name: 'Spain',
        slug: 'spain',
        flagCode: 'es',
        schoolCount: 310,
        cities: 'Barcelona, Madrid, Málaga',
        nanaNote: '"Spain has a large, well-established international school market. Barcelona and Madrid are top destinations for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Switzerland',
        slug: 'switzerland',
        flagCode: 'ch',
        schoolCount: 162,
        cities: 'Lausanne, Montreux, Leysin',
        nanaNote: '"Premium boarding, multilingual, stunning alpine campuses. Worth every franc."',
        imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Germany',
        slug: 'germany',
        flagCode: 'de',
        schoolCount: 97,
        cities: 'Berlin, Munich, Hamburg',
        nanaNote: '"Strong STEM focus. Excellent university pathways to European institutions."',
        imageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'France',
        slug: 'france',
        flagCode: 'fr',
        schoolCount: 96,
        cities: 'Paris, Lyon, Nice',
        nanaNote: '"Paris has a strong network of international schools. EABJM and the American School of Paris are well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Netherlands',
        slug: 'netherlands',
        flagCode: 'nl',
        schoolCount: 43,
        cities: 'Amsterdam, The Hague, Rotterdam',
        nanaNote: '"The Hague has a high concentration of international schools, driven by its diplomatic community."',
        imageUrl: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Italy',
        slug: 'italy',
        flagCode: 'it',
        schoolCount: 24,
        cities: 'Rome, Milan, Florence',
        nanaNote: '"Culture-rich campuses. Great for arts and humanities-focused families."',
        imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ireland',
        slug: 'ireland',
        flagCode: 'ie',
        schoolCount: 11,
        cities: 'Dublin, Cork',
        nanaNote: '"English-medium, welcoming, and increasingly popular with Asian families. Dublin has good international options."',
        imageUrl: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Turkey',
        slug: 'turkey',
        flagCode: 'tr',
        schoolCount: 5,
        cities: 'Istanbul, Ankara',
        nanaNote: '"Istanbul has a small but growing international school community with strong IB options."',
        imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Austria',
        slug: 'austria',
        flagCode: 'at',
        schoolCount: 3,
        cities: 'Vienna, Salzburg',
        nanaNote: '"A hidden gem. AMADEUS International School in Vienna is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1516550893885-985c836c9b3c?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'east-asia',
    slug: 'east-asia',
    name: 'East Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=85&auto=format&fit=crop',
    description: '5 powerhouse education markets — from Hong Kong\'s British-style schools to Japan\'s disciplined international environment. China\'s international school scene has grown remarkably in major cities.',
    nanaQuoteLabel: 'Nana\'s take on East Asia',
    nanaQuote: '"Hong Kong gives you British education quality within Asia — ideal for families who want the best of both worlds. Japan is safe, structured and increasingly international. For China, stick to the established international schools in Shanghai and Beijing."',
    nanaQuoteStrong: 'Hong Kong gives you British education quality within Asia',
    stats: { countries: 5, schools: 955 },
    countries: [
      {
        name: 'China',
        slug: 'china',
        flagCode: 'cn',
        schoolCount: 533,
        cities: 'Shanghai, Beijing, Shenzhen',
        nanaNote: '"Large international school network in major cities. Stick to the established names."',
        imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Hong Kong',
        slug: 'hong-kong',
        flagCode: 'hk',
        schoolCount: 151,
        cities: 'Hong Kong Island, Kowloon',
        nanaNote: '"Gateway to Asia. British-style education with an Asian edge."',
        imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Japan',
        slug: 'japan',
        flagCode: 'jp',
        schoolCount: 212,
        cities: 'Tokyo, Osaka, Yokohama',
        nanaNote: '"Safe, disciplined, growing international scene. My top pick in the region."',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Taiwan',
        slug: 'taiwan',
        flagCode: 'tw',
        schoolCount: 20,
        cities: 'Taipei',
        nanaNote: '"Underrated destination. Safe, affordable, and a genuinely international city."',
        imageUrl: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'South Korea',
        slug: 'south-korea',
        flagCode: 'kr',
        schoolCount: 39,
        cities: 'Seoul, Busan',
        nanaNote: '"Korea\'s international schools are small but impressive. Seoul has several strong options."',
        imageUrl: 'https://images.unsplash.com/photo-1517154421773-0855edd8b212?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'middle-east',
    slug: 'middle-east',
    name: 'Middle East',
    nameItalicPart: 'East',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85&auto=format&fit=crop',
    description: '8 countries with world-class international schools — the UAE and Qatar have invested heavily in education infrastructure. Excellent facilities, competitive fees, and strong university outcomes.',
    nanaQuoteLabel: 'Nana\'s take on the Middle East',
    nanaQuote: '"Dubai and Abu Dhabi have genuinely excellent international schools — the facilities rival anything I have seen in Switzerland. GEMS Education runs many strong campuses across the region. Qatar\'s Education City is unique in the world for having top university branches on one campus."',
    nanaQuoteStrong: 'Dubai and Abu Dhabi have genuinely excellent international schools',
    stats: { countries: 7, schools: 448 },
    countries: [
      {
        name: 'United Arab Emirates',
        slug: 'uae',
        flagCode: 'ae',
        schoolCount: 81,
        cities: 'Dubai, Abu Dhabi, Sharjah',
        nanaNote: '"Outstanding facilities. GEMS, SABIS and British-style schools everywhere."',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Qatar',
        slug: 'qatar',
        flagCode: 'qa',
        schoolCount: 102,
        cities: 'Doha, Education City',
        nanaNote: '"Education City is one of the most unique campuses in the world."',
        imageUrl: 'https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Saudi Arabia',
        slug: 'saudi-arabia',
        flagCode: 'sa',
        schoolCount: 162,
        cities: 'Riyadh, Jeddah, Khobar',
        nanaNote: '"Expanding rapidly. Strong American and British curriculum options in major cities."',
        imageUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Kuwait',
        slug: 'kuwait',
        flagCode: 'kw',
        schoolCount: 7,
        cities: 'Kuwait City',
        nanaNote: '"Smaller market but with some established British and American schools."',
        imageUrl: 'https://images.unsplash.com/photo-1543788060-86d18e28b530?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bahrain',
        slug: 'bahrain',
        flagCode: 'bh',
        schoolCount: 36,
        cities: 'Manama',
        nanaNote: '"Small, safe, and welcoming. Good options for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1574031908-a6d98e0aad1a?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Oman',
        slug: 'oman',
        flagCode: 'om',
        schoolCount: 34,
        cities: 'Muscat',
        nanaNote: '"Quiet and safe. The British School Muscat is a standout."',
        imageUrl: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Jordan',
        slug: 'jordan',
        flagCode: 'jo',
        schoolCount: 26,
        cities: 'Amman',
        nanaNote: '"Amman has a well-established international school community. A hub for diplomatic and NGO families."',
        imageUrl: 'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'oceania',
    slug: 'oceania',
    name: 'Oceania',
    nameItalicPart: 'Oceania',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=85&auto=format&fit=crop',
    description: 'Australia and New Zealand offer world-class education in a relaxed, safe environment. Strong universities, outdoor lifestyle, and welcoming communities for international families.',
    nanaQuoteLabel: 'Nana\'s take on Oceania',
    nanaQuote: '"Australia and New Zealand are seriously underrated as study destinations. The schools are excellent, the outdoor lifestyle is unmatched, and the universities rank among the world\'s best. Sydney and Melbourne both have strong international school networks."',
    nanaQuoteStrong: 'Australia and New Zealand are seriously underrated',
    stats: { countries: 2, schools: 21 },
    countries: [
      {
        name: 'Australia',
        slug: 'australia',
        flagCode: 'au',
        schoolCount: 13,
        cities: 'Sydney, Melbourne, Brisbane',
        nanaNote: '"World-class universities, safe environment, strong IB and A-Level programmes."',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'New Zealand',
        slug: 'new-zealand',
        flagCode: 'nz',
        schoolCount: 8,
        cities: 'Auckland, Wellington',
        nanaNote: '"Outstanding quality of life. Auckland International College is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
    ],
  },
  {
    id: 'americas',
    slug: 'americas',
    name: 'Americas',
    nameItalicPart: 'Americas',
    heroImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1400&q=85&auto=format&fit=crop',
    description: 'From New England\'s elite prep schools to Canada\'s welcoming international campuses — the Americas offer a distinct education culture. US boarding schools are among the most prestigious in the world.',
    nanaQuoteLabel: 'Nana\'s take on the Americas',
    nanaQuote: '"US boarding schools like Exeter, Andover and Choate have a prestige all their own. If your child wants to attend an Ivy League university, an American prep school gives a real advantage. Canada is an excellent alternative — strong quality, lower fees, and a welcoming immigration path."',
    nanaQuoteStrong: 'US boarding schools have a prestige all their own',
    stats: { countries: 10, schools: 192 },
    countries: [
      {
        name: 'United States',
        slug: 'usa',
        flagCode: 'us',
        schoolCount: 56,
        cities: 'New England, New York, California',
        nanaNote: '"Ivy League pathway. Phillips Exeter, Andover, Choate — these names open every door."',
        imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Canada',
        slug: 'canada',
        flagCode: 'ca',
        schoolCount: 31,
        cities: 'Toronto, Vancouver, Montreal',
        nanaNote: '"Strong quality, welcoming to international families, excellent universities."',
        imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Mexico',
        slug: 'mexico',
        flagCode: 'mx',
        schoolCount: 20,
        cities: 'Mexico City, Monterrey',
        nanaNote: '"Strong American-curriculum schools in Mexico City for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Brazil',
        slug: 'brazil',
        flagCode: 'br',
        schoolCount: 17,
        cities: 'São Paulo, Rio de Janeiro',
        nanaNote: '"São Paulo has a thriving international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Argentina',
        slug: 'argentina',
        flagCode: 'ar',
        schoolCount: 22,
        cities: 'Buenos Aires',
        nanaNote: '"Buenos Aires has a long-established international school scene. Lincoln International Academy is a standout."',
        imageUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Colombia',
        slug: 'colombia',
        flagCode: 'co',
        schoolCount: 11,
        cities: 'Bogotá, Medellín',
        nanaNote: '"Bogotá has solid bilingual international schools. A growing destination for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1533236897111-3e94666b2edf?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Chile',
        slug: 'chile',
        flagCode: 'cl',
        schoolCount: 10,
        cities: 'Santiago',
        nanaNote: '"Santiago has well-run bilingual and IB schools. The Redland School is particularly strong."',
        imageUrl: 'https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Peru',
        slug: 'peru',
        flagCode: 'pe',
        schoolCount: 9,
        cities: 'Lima',
        nanaNote: '"Lima\'s international schools are well-regarded. Colegio Franklin D. Roosevelt is the flagship American school."',
        imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Costa Rica',
        slug: 'costa-rica',
        flagCode: 'cr',
        schoolCount: 11,
        cities: 'San José',
        nanaNote: '"A favourite for families who want English-medium schooling in a safe, nature-rich environment."',
        imageUrl: 'https://images.unsplash.com/photo-1538978500879-0caab543d71c?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ecuador',
        slug: 'ecuador',
        flagCode: 'ec',
        schoolCount: 5,
        cities: 'Quito, Guayaquil',
        nanaNote: '"Quito has a handful of strong international schools. The Cotopaxi Academy is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1484627147104-f5197bcd6651?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'south-asia',
    slug: 'south-asia',
    name: 'South Asia',
    nameItalicPart: 'Asia',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1400&q=85&auto=format&fit=crop',
    description: 'India leads South Asia with a rapidly growing international school sector in major cities. Strong academic culture, competitive fees, and increasingly strong university pathways.',
    nanaQuoteLabel: 'Nana\'s take on South Asia',
    nanaQuote: '"India\'s international school sector has grown enormously. Mumbai, Bangalore and Delhi all have strong options. Sri Lanka is a lovely, safe choice for families who want a quieter pace. The region is seriously underrated for quality and value."',
    nanaQuoteStrong: 'India\'s international school sector has grown enormously',
    stats: { countries: 4, schools: 446 },
    countries: [
      {
        name: 'India',
        slug: 'india',
        flagCode: 'in',
        schoolCount: 433,
        cities: 'Mumbai, Bangalore, Delhi',
        nanaNote: '"Strong growth in IB schools. Pathways Learning Academy and Oberoi International are standouts."',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Sri Lanka',
        slug: 'sri-lanka',
        flagCode: 'lk',
        schoolCount: 2,
        cities: 'Colombo',
        nanaNote: '"Affordable, safe, and English-medium. Good for families who value a calmer pace."',
        imageUrl: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Pakistan',
        slug: 'pakistan',
        flagCode: 'pk',
        schoolCount: 7,
        cities: 'Karachi, Lahore, Islamabad',
        nanaNote: '"British curriculum schools in major cities. Beaconhouse is well-established."',
        imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Bangladesh',
        slug: 'bangladesh',
        flagCode: 'bd',
        schoolCount: 4,
        cities: 'Dhaka',
        nanaNote: '"Growing international community in Dhaka. Good for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1555990793-da11153b6ec9?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
  {
    id: 'africa',
    slug: 'africa',
    name: 'Africa',
    nameItalicPart: 'Africa',
    heroImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&q=85&auto=format&fit=crop',
    description: 'Africa\'s international school sector is anchored by Kenya, Egypt and South Africa — three markets with long-established British and American curriculum schools.',
    nanaQuoteLabel: 'Nana\'s take on Africa',
    nanaQuote: '"Nairobi is one of the most underrated international school cities in the world. The Aga Khan Academy and Brookhouse School are genuinely world-class. South Africa has strong British-style schools with excellent outdoor programmes."',
    nanaQuoteStrong: 'Nairobi is one of the most underrated international school cities',
    stats: { countries: 12, schools: 144 },
    countries: [
      {
        name: 'Kenya',
        slug: 'kenya',
        flagCode: 'ke',
        schoolCount: 30,
        cities: 'Nairobi, Mombasa',
        nanaNote: '"Nairobi\'s international school scene is world-class. Aga Khan Academy is exceptional."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Egypt',
        slug: 'egypt',
        flagCode: 'eg',
        schoolCount: 36,
        cities: 'Cairo, Alexandria',
        nanaNote: '"Cairo has a large, well-established international school community."',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'South Africa',
        slug: 'south-africa',
        flagCode: 'za',
        schoolCount: 3,
        cities: 'Cape Town, Johannesburg',
        nanaNote: '"British-style schools with excellent outdoor programmes and stunning campuses."',
        imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=500&q=80&auto=format&fit=crop',
        isFeatured: true,
      },
      {
        name: 'Nigeria',
        slug: 'nigeria',
        flagCode: 'ng',
        schoolCount: 25,
        cities: 'Lagos, Abuja',
        nanaNote: '"Lagos is West Africa\'s education hub. Several strong British-curriculum schools."',
        imageUrl: 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Tanzania',
        slug: 'tanzania',
        flagCode: 'tz',
        schoolCount: 8,
        cities: 'Dar es Salaam, Arusha',
        nanaNote: '"International schools in Dar es Salaam are strong and well-resourced."',
        imageUrl: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Uganda',
        slug: 'uganda',
        flagCode: 'ug',
        schoolCount: 14,
        cities: 'Kampala',
        nanaNote: '"Kampala has a small but growing international school community. Good for expat families in East Africa."',
        imageUrl: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Morocco',
        slug: 'morocco',
        flagCode: 'ma',
        schoolCount: 12,
        cities: 'Casablanca, Rabat',
        nanaNote: '"Casablanca has well-established French and British curriculum schools. A growing destination for international families."',
        imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ethiopia',
        slug: 'ethiopia',
        flagCode: 'et',
        schoolCount: 4,
        cities: 'Addis Ababa',
        nanaNote: '"Addis Ababa is Africa\'s diplomatic hub. The International Community School is the top choice for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Ghana',
        slug: 'ghana',
        flagCode: 'gh',
        schoolCount: 3,
        cities: 'Accra',
        nanaNote: '"Accra has a small but well-regarded international school community. Ideal for West Africa postings."',
        imageUrl: 'https://images.unsplash.com/photo-1578328819058-a6d93bb26285?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Rwanda',
        slug: 'rwanda',
        flagCode: 'rw',
        schoolCount: 3,
        cities: 'Kigali',
        nanaNote: '"Kigali is clean, safe, and increasingly international. A surprising gem for expat families."',
        imageUrl: 'https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Zambia',
        slug: 'zambia',
        flagCode: 'zm',
        schoolCount: 3,
        cities: 'Lusaka',
        nanaNote: '"Lusaka has a handful of British-curriculum schools serving the expat and NGO community."',
        imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=500&q=80&auto=format&fit=crop',
      },
      {
        name: 'Lebanon',
        slug: 'lebanon',
        flagCode: 'lb',
        schoolCount: 3,
        cities: 'Beirut',
        nanaNote: '"Beirut has a long tradition of elite private schooling. The American Community School is well-regarded."',
        imageUrl: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=500&q=80&auto=format&fit=crop',
      },
    ],
  },
]

export function getRegionData(slug: string): RegionData | undefined {
  return REGIONS_DATA.find(r => r.slug === slug)
}
