import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import fs from 'fs'
import path from 'path'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import { getCountryPageMeta } from '@/lib/countryMeta'
import { getSchoolsForCountryPage, getCountrySchoolCounts } from '@/lib/schools'
import { supabase } from '@/lib/supabase'
import { REGIONS_DATA } from '@/lib/regionData'
import CountryPageClient from '@/components/country/CountryPageClient'

interface Props { params: { slug: string } }

// Load country intros from JSON file (generated by scripts/generate-country-intros.js)
function loadCountryIntros(): Record<string, string> {
  try {
    const filePath = path.join(process.cwd(), 'data', 'country-intros.json')
    if (!fs.existsSync(filePath)) return {}
    const raw = JSON.parse(fs.readFileSync(filePath, 'utf8'))
    // Shape: { [country]: { intro: string, ... } }
    return Object.fromEntries(
      Object.entries(raw).map(([k, v]: [string, any]) => [k, v.intro ?? ''])
    )
  } catch (_) {
    return {}
  }
}

export async function generateStaticParams() {
  const counts = await getCountrySchoolCounts()
  const countriesWithData = new Set(Object.keys(counts).filter(c => counts[c] > 0))
  return REGIONS_DATA.flatMap(r =>
    r.countries
      .filter(c => countriesWithData.has(c.name))
      .map(c => ({ slug: c.slug }))
  )
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const meta = getCountryPageMeta(params.slug)
  if (!meta) return { title: 'Country not found · nanasays' }

  const { count } = await supabase
    .from('schools')
    .select('id', { count: 'exact', head: true })
    .eq('country', meta.name)
    .eq('is_international', true)

  const countLabel = count && count > 0 ? `${count}+ ` : ''

  return {
    title: `International Schools in ${meta.name} — ${countLabel}Fees & Reviews`,
    description: `Browse ${countLabel}international schools in ${meta.name}. Compare fees, curriculum, boarding options and admissions — all on NanaSays.`,
    openGraph: { images: [{ url: meta.heroImage }] },
    other: { robots: 'max-snippet:-1, max-image-preview:large, max-video-preview:-1' },
  }
}

export const revalidate = 3600 // revalidate country pages every hour

export default async function CountryPage({ params }: Props) {
  const meta = getCountryPageMeta(params.slug)
  if (!meta) notFound()

  const [schools, feeData, boardingCount, topCityData, curriculumData, feeTableData] = await Promise.all([
    getSchoolsForCountryPage(meta.name),
    supabase.from('schools').select('fees_usd_min, fees_usd_max')
      .eq('country', meta.name).eq('is_international', true)
      .not('fees_usd_min', 'is', null).gte('fees_usd_min', 1000),
    supabase.from('schools').select('*', { count: 'exact', head: true })
      .eq('country', meta.name).eq('is_international', true).eq('boarding', true),
    supabase.from('schools').select('city')
      .eq('country', meta.name).eq('is_international', true).not('city', 'is', null),
    supabase.from('schools').select('curriculum')
      .eq('country', meta.name).eq('is_international', true).not('curriculum', 'is', null),
    supabase.from('schools')
      .select('name, slug, curriculum, fees_usd_min, fees_usd_max, city, age_min, age_max')
      .eq('country', meta.name).eq('is_international', true)
      .not('fees_usd_min', 'is', null).gte('fees_usd_min', 1000)
      .order('fees_usd_min', { ascending: false })
      .limit(10),
  ])

  if (!schools.length) notFound()

  // ── Derived FAQ data ────────────────────────────────────────────────────────
  const totalCount = schools.length

  const feeMins = (feeData.data ?? []).map(r => r.fees_usd_min).filter(Boolean)
  const feeMaxes = (feeData.data ?? []).map(r => r.fees_usd_max ?? r.fees_usd_min).filter(Boolean)
  const feeMin = feeMins.length ? Math.min(...feeMins) : null
  const feeMax = feeMaxes.length ? Math.max(...feeMaxes) : null
  const feeAnswer = feeMin && feeMax
    ? `Annual fees at international schools in ${meta.name} range from $${Math.round(feeMin / 1000)}k to $${Math.round(feeMax / 1000)}k per year.`
    : `Fees vary by school. Use the NanaSays filter to search by budget.`

  const boarding = boardingCount.count ?? 0

  // Top city
  const cityCounts: Record<string, number> = {}
  for (const row of topCityData.data ?? []) {
    if (row.city) cityCounts[row.city] = (cityCounts[row.city] || 0) + 1
  }
  const topCity = Object.entries(cityCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null
  const topCityCount = topCity ? cityCounts[topCity] : 0

  // IB count
  const IB_VARIANTS = ['IB', 'IB Primary Years Programme', 'IB Middle Years Programme', 'IB Diploma Programme', 'International Baccalaureate', 'IB Career-related Programme']
  let ibCount = 0
  const curricula = new Set<string>()
  for (const row of curriculumData.data ?? []) {
    let hasIB = false
    for (const c of row.curriculum ?? []) {
      curricula.add(c.split(' ')[0])
      if (IB_VARIANTS.includes(c)) hasIB = true
    }
    if (hasIB) ibCount++
  }
  const topCurricula = Array.from(curricula).slice(0, 4).join(', ')

  // ── Schema ──────────────────────────────────────────────────────────────────
  const itemListSchema = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: `International Schools in ${meta.name}`,
    description: meta.nanaNote,
    numberOfItems: schools.length,
    itemListElement: schools.slice(0, 20).map((s, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: s.name,
      url: `https://nanasays.school/schools/${s.slug}`,
    })),
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://nanasays.school' },
      { '@type': 'ListItem', position: 2, name: 'Browse Regions', item: 'https://nanasays.school/#regions' },
      { '@type': 'ListItem', position: 3, name: meta.name, item: `https://nanasays.school/countries/${params.slug}` },
    ],
  }

  // FAQ schema — only inject questions where we have real data answers
  const faqItems = []
  faqItems.push({
    '@type': 'Question',
    name: `How many international schools are in ${meta.name}?`,
    acceptedAnswer: { '@type': 'Answer', text: `${totalCount} international schools are listed in the NanaSays directory for ${meta.name}.` },
  })
  if (feeMin) {
    faqItems.push({
      '@type': 'Question',
      name: `What do international schools cost in ${meta.name}?`,
      acceptedAnswer: { '@type': 'Answer', text: feeAnswer },
    })
  }
  if (topCurricula) {
    faqItems.push({
      '@type': 'Question',
      name: `What curricula are available at international schools in ${meta.name}?`,
      acceptedAnswer: { '@type': 'Answer', text: `International schools in ${meta.name} offer a range of curricula including ${topCurricula}. Use the NanaSays curriculum filter to narrow your search.` },
    })
  }
  if (boarding > 0) {
    faqItems.push({
      '@type': 'Question',
      name: `Are there boarding schools in ${meta.name}?`,
      acceptedAnswer: { '@type': 'Answer', text: `${boarding} international school${boarding > 1 ? 's' : ''} in ${meta.name} offer${boarding === 1 ? 's' : ''} boarding.` },
    })
  }
  if (topCity) {
    faqItems.push({
      '@type': 'Question',
      name: `Which city in ${meta.name} has the most international schools?`,
      acceptedAnswer: { '@type': 'Answer', text: `${topCity} has the highest concentration of international schools in ${meta.name} with ${topCityCount} listed schools.` },
    })
  }
  if (ibCount > 0) {
    faqItems.push({
      '@type': 'Question',
      name: `Does ${meta.name} have IB schools?`,
      acceptedAnswer: { '@type': 'Answer', text: `${ibCount} IB-authorised international school${ibCount > 1 ? 's' : ''} ${ibCount > 1 ? 'are' : 'is'} listed in ${meta.name} on NanaSays.` },
    })
  }

  const faqSchema = faqItems.length >= 4 ? {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqItems,
  } : null

  // ── Intro copy ──────────────────────────────────────────────────────────────
  const countryIntros = loadCountryIntros()
  const countryIntro = countryIntros[meta.name] ?? null

  const feeTableSchools = (feeTableData.data ?? []).map(s => ({
    name: s.name,
    slug: s.slug,
    curriculum: s.curriculum?.[0] ?? null,
    fees_usd_min: s.fees_usd_min,
    fees_usd_max: s.fees_usd_max,
    city: s.city,
    age_min: s.age_min,
    age_max: s.age_max,
  }))

  const metaWithIntro = {
    ...meta,
    countryIntro: countryIntro ?? undefined,
    feeTableSchools: feeTableSchools.length >= 5 ? feeTableSchools : undefined,
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      {faqSchema && (
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      )}
      <Nav />
      <CountryPageClient meta={metaWithIntro} schools={schools} />
      <Footer />
    </>
  )
}
